name: Build LaTeX Resume

on:
  push:
    branches:
      - main   # Runs workflow when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex   # 👈 your LaTeX file name here

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: cv.pdf        # 👈 compiled output name
